<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Ad-Hoc;AppStore;Debug;Release</Configurations>
    <ApplicationIcon>..\MixItUp.WPF\Logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <PackageReference Include="MaterialDesignColors" Version="2.0.6" />
    <PackageReference Include="MaterialDesignThemes" Version="4.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MixItUp.Base\MixItUp.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\MixItUp.WPF\Logo.ico">
      <Link>Logo.ico</Link>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\MixItUp.WPF\Logo.png">
      <Link>Logo.png</Link>
    </Resource>
  </ItemGroup>
</Project>